# Generated by Django 2.2.16 on 2022-11-12 10:55

from django.db import migrations, models
import reviews.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221111_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.models.validators.validate_year], verbose_name='Year'),
        ),
    ]
